
<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="product">Product</label>
    <select name="product" id="input"  class="form-select" aria-label="Default select example">
        <?php foreach($products as $product): ?>
            <option 
            <?php if($product->id==$e->product){
                echo ' selected="selected" ';
            } ?>
            value="<?=$product->id?>">
                <?=$product->name?>
            </option>
        <?php endforeach;?>
    </select>
</div>


<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="worker">Employed</label>
    <select name="worker" id="input"  class="form-select" aria-label="Default select example">
        <?php foreach($workers as $worker): ?>
            <option 
            <?php if($worker->id==$e->worker){
                echo ' selected="selected" ';
            } ?>
            value="<?=$worker->id?>">
                <?=$worker->surname?> <?=$worker->name?>
            </option>
        <?php endforeach;?>
    </select>
</div>
    

<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="amount">Amount</label>
    <input type="text" class="form-control" value="" name="amount" id="amount">
</div>


<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="date">Date</label>
    <input type="date" class="form-control" value="" name="date" id="date">
</div>



