<form action="<?php echo App::config('url') ?>cycle/change/<?=$e->id?>" 
        method="post">
    <div class="grid-x grid-padding-x">
        <div class="large-6 cell">
            <?php include_once 'basicData.phtml'?>
        </div>
        

        
    </div>

    <?=$message?><br>

    <button type="submit" class="btn btn-outline-success"  data-bs-target="#staticBackdrop">
    Save Cycle
    </button>

    <a href="<?=App::config('url')?>cycle/abort/<?=$e->id?>">
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Abort
    </button></a>
</form>


