<form action="<?php echo App::config('url') ?>cycle/change/<?=$e->id?>" 
        method="post">
    <div class="grid-x grid-padding-x">
        <div class="large-6 cell">
            <?php include_once 'basicData.phtml'?>
        </div>
        <div class="large-6 cell">
        <?php include_once 'workerList.phtml'?>
        </div>

        <div class="large-6 cell">
            <a href="<?=App::config('url')?>cycle/abort/<?=$e->id?>"
            class="button alert expanded">Abort</a>
        </div>
        <div class="large-6 cell">
            <input type="submit" class="button success expanded" 
            value="Spremi">
        </div>
    </div>
</form>