<h3 class="display-3">Production Cycles</h3>
<a href="<?=App::config('url')?>cycle/new"><button type="button" class="btn btn-outline-primary btn-lg">Add new</button></a>
<br>
***
<div class="mb-3 row" style="max-width:600px; margin: auto;">
  <form action="" method="get">
      <input class="form-control" type="text" name="condition" id="condition"
      placeholder="Employee name, surname or Product name"
      value="<?=$condition?>" >
  </form>
</div>
<hr>
<?php include 'pagination.phtml' ?>
<div class="row justify-content-md-center">
    <?php foreach($data as $d): ?>
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h5><?=$d->name?></h5>
                    <h5><?=$d->surname?></h5>
                    <h2><?=$d->product?></h2>
                    <h5>Amount: <?=$d->amount?></h5>
                    <h5>Date: <?=$d->date?></h5>

                        <a href="<?=App::config('url')?>cycle/change/<?=$d->id?>"><i class="bi bi-pencil-square"></i></a>
                    <?php if(App::admin()): ?>
                        <a onclick="return confirm('Delete cycle <?=$d->surname?> <?=$d->product?>?');"
                        href="<?=App::config('url')?>cycle/delete/<?=$d->id?>"><i class="bi bi-trash3-fill"></i></a>
                    <?php else: ?>
                        <i title="Can not delete production cycle" 
                        class="bi bi-trash3-fill" style="color: gray"></i>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach;?>
</div>

<br>
<?php include 'pagination.phtml' ?>