<h3 class="display-3">Production Cycles</h3>
<a href="<?=App::config('url')?>cycle/new"><button type="button" class="btn btn-outline-primary btn-lg">Add new</button></a>
<br>
***
<hr>
<div class="row">
    <?php foreach($data as $d): ?>
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h5><?=$d->name?></h5>
                    <h5><?=$d->surname?></h5>
                    <h2><?=$d->product?></h2>
                    <h5>Amount: <?=$d->amount?></h5>
                    <h5><?=$d->date?></h5>

                    <a href="<?=App::config('url')?>cycle/change/<?=$d->id?>"><i class="bi bi-pencil-square"></i></a>
                    <?php if(App::admin()): ?>
                    <a onclick="return confirm('Delete cycle <?=$d->name?>?');"
                    href="<?=App::config('url')?>cycle/delete/<?=$d->id?>"><i class="bi bi-trash3-fill"></i></a>
                    <?php else: ?>
                    <i title="Can not delete production cycle" 
                    class="bi bi-trash3-fill" style="color: gray"></i>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach;?>
</div>

