<legend>Insert new Cycle</legend>

<form action="" method="post">
    
    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="worker_shift">Employed</label>
        <!--<input class="form-control" type="text" worker_shift="worker_shift" id="worker_shift" value="<?php echo App::operator()?>" aria-label="Disabled input example" disabled>-->
        <input type="text" name="worker_shift" class="form-control"  id="worker_shift" value="<?=$e->worker_shift?>">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="product">Product</label>
        <select class="form-select form-select-md" name="product" id="product">
            <?php foreach($products as $product): ?>
                <option 
                <?php if($product->id==$e->product){
                    echo ' selected="selected" ';
                } ?>
                value="<?=$product->id?>">
                    <?=$product->name?>
                </option>
            <?php endforeach;?>
        </select>
        <!--<input type="text" class="form-control" value="<?=$e->product?>" name="product" id="product">-->
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="amount">Amount</label>
        <input type="text" class="form-control" value="<?=$e->amount?>" name="amount" id="amount">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="date">Date</label>
        <input type="date" class="form-control" value="<?=$e->date?>" name="date" id="date">
    </div>


    <!-- Button trigger modal -->
    <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Add Cycle
    </button>

    <a href="<?=App::config('url')?>cycle/index">
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Abort
    </button></a>

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Add Cycle</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Save changes!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>
    
</form>