<div class="row justify-content-md-center">

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <?php if($page===1): ?>
                <li class="page-item disabled"><a class="page-link" href="#" >Prev</a></li>
            <?php else: ?>
                <li class="page-item "><a class="page-link" href="<?=App::config('url')?>cycle/index?page=<?php echo $page-1; ?>&condition=<?=$condition?>">Prev</a></li>
            <?php endif;?>

                <li class="page-item page-item active"><a class="page-link" href="#"><?=$page?></a></li>
                        
            <?php if($page===$last): ?>
                <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            <?php else: ?>
                <li class="page-item"><a class="page-link" href="<?=App::config('url')?>cycle/index?page=<?php echo $page+1; ?>&condition=<?=$condition?>">Next</a></li>
            <?php endif;?>
        </ul>
    </nav>

</div>