<legend>Insert New Shift</legend>

<form action="" method="post">
    
    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="name">Name*</label>
        <input type="text" name="name" class="form-control"  id="name" value="<?=$e->name?>">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="duration">Duration</label>
        <input type="text" name="duration" class="form-control"  id="duration" value="<?=$e->duration?>">
    </div>

    

    <?=$message?><br>

    <!-- Button trigger modal -->
    <button type="submit" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Add Shift
    </button>

    <a href="<?=App::config('url')?>shift/index">
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Abort
    </button></a>
    
</form>