<nav class="navbar sticky-top bg-body-tertiary">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?=App::config('url');?>"><strong><?=App::config('nameApp');?></strong></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="<?=App::config('url');?>index/contact">Kontakt</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?=App::config('url');?>index/onama">O nama</a>
                </li>
                </ul>
            </div>                      
        </div>        
    </nav>                   
        <div class="d-grid gap-2 d-md-flex justify-content-md-end" style="margin-right: 20px;">
            <a href="<?=App::config('url');?>index/prijava"><button type="button" class="btn btn-secondary btn-md">LogIn</button></a>
        </div>         
</nav>