<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="name">Name*</label>
    <input type="text" name="name" class="form-control"  id="name" value="<?=$e->name?>">
</div>

<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="surname">Surname*</label>
    <input type="text" name="surname" class="form-control"  id="surname" value="<?=$e->surname?>">
</div>

<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="oib">Oib</label>
    <input type="text" class="form-control" value="<?=$e->oib?>" name="oib" id="oib">
</div>

<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="contractnumber">Contractnumber</label>
    <input type="text" class="form-control" value="<?=$e->contractnumber?>" name="contractnumber" id="contractnumber">
</div>

<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="iban">IBAN</label>
    <input type="text" class="form-control" value="<?=$e->iban?>" name="iban" id="iban">
</div>

<div class="mb-3 row" style="max-width:400px; margin: auto;">
    <label for="shift">Shift</label>
    <select name="shift" id="input"  class="form-select" aria-label="Default select example">
        <?php foreach($shifts as $shift): ?>
            <option 
            <?php if($shift->id==$e->shift){
                echo ' selected="selected" ';
            } ?>
            value="<?=$shift->id?>">
                <?=$shift->name?>
            </option>
        <?php endforeach;?>
    </select>
</div>

