<form action="<?php echo App::config('url') ?>worker/change/<?=$e->id?>" method="post">
    
    <div class="large-6 cell">
        <?php include_once 'basicData.phtml'?>
    </div>
    
    

    <?=$message?><br>

    <!-- Button trigger modal -->
    <button type="submit" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Save Employee
    </button>

    <a href="<?=App::config('url')?>worker/abort/<?=$e->id?>">
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Abort
    </button></a>
</form>