<h3 class="display-3">Employees</h3>
<a href="new"><button type="button" class="btn btn-outline-primary btn-lg">Add new employee</button></a>
<br>
***
<hr>

<div class="row">
<?php foreach($data as $d): ?>
  <div class="col-lg-3">
    <div class="card">
      <div class="card-body">
            <h2><?=$d->name?></h2>
            <h2><?=$d->surname?></h2>
            <h5>Shift: <?=$d->shift?></h5>
            <h5>OIB: <?=$d->oib?></h5>
            <h5>Contract: <?=$d->contractnumber?></h5>
            <h5>IBAN: <?=$d->iban?></h5>

            <a href="<?=App::config('url')?>worker/change/<?=$d->id?>"><i class="bi bi-pencil-square"></i></a>
            <a onclick="return confirm('Delete employee <?=$d->name?> <?=$d->surname?>?');"
            href="<?=App::config('url')?>worker/delete/<?=$d->id?>"><i class="bi bi-trash3-fill"></i></a>
      </div>
    </div>
  </div>
  <?php endforeach;?>
</div>