<legend>Update Product</legend>

<form action="" method="post">
    
    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="name">Product Name*</label>
        <input type="text" name="name" class="form-control"  id="name" value="<?=$e->name?>">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="color">Color</label>
        <input type="text" class="form-control" value="<?=$e->color?>" name="color" id="color">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="price">Price*</label>
        <input type="text" class="form-control" value="<?=$e->price?>" name="price" id="price">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="customer">Customer</label>
        <input type="text" class="form-control" value="<?=$e->customer?>" name="customer" id="customer">
    </div>

    <?=$message?><br>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Update Product
    </button>

    <a href="<?=App::config('url')?>product/index">
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Abort
    </button></a>

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Update Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Save changes!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>
    
</form><br>
