<h3 class="display-3">Products</h3>
<?php if(App::admin()): ?><a href="<?=App::config('url')?>product/new"><button type="button" class="btn btn-outline-primary btn-lg">Add new product</button></a><?php endif; ?>
<br>
***
<hr>

<?php if(App::admin()): ?>
    <div class="row">
        <?php foreach($data as $d): ?>
            <div class="col-lg-3">
                <div class="card">
                    <div class="card-body">
                            <h2><?=$d->name?></h2>
                            <h5><?=$d->color?></h5>
                            <h5><?=$d->price?> (€)</h5>
                            <h5>Customer: <?=$d->customer?></h5>

                            <a href="<?=App::config('url')?>product/change/<?=$d->id?>"><i class="bi bi-pencil-square"></i></a>
                            <a onclick="return confirm('Delete product <?=$d->name?>?');"
                            href="<?=App::config('url')?>product/delete/<?=$d->id?>"><i class="bi bi-trash3-fill"></i></a>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
    </div>
<?php else: ?>
    <div class="card">
        <table class="table table-striped">
            <thead>
                <tr class="table-warning">
                    <th scope="col">Name</th>
                    <th scope="col">Color</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($data as $d):?>
                    <tr>
                        <td><?=$d->name?></td>
                        <td><?=$d->color?></td>
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
<?php endif; ?>