<h3 class="display-3">Products</h3>
<?php if(App::admin()): ?><a href="<?=App::config('url')?>product/new"><button type="button" class="btn btn-outline-primary btn-lg">Add new product</button></a><?php endif; ?>
<br>
***
<div class="mb-3 row" style="max-width:600px; margin: auto;">
  <form action="" method="get">
      <input class="form-control" type="text" name="condition" id="condition"
      placeholder="Product name"
      value="<?=$condition?>" >
  </form>
</div>
<hr>

<?php include 'pagination.phtml' ?>

<?php if(App::admin()): ?>
    <div class="row">
        <?php foreach($data as $d): ?>
            <div class="col-lg-3">
                <div class="card">
                    <div class="card-body">
                            <h2><?=$d->name?></h2>
                            <h5><?=$d->color?></h5>
                            <h5><?=$d->price?> (€)</h5>
                            <h5>Customer: <?=$d->customer?></h5>

                                <a href="<?=App::config('url')?>product/change/<?=$d->id?>"><i class="bi bi-pencil-square"></i></a>
                            <?php if($d->cycles==0): ?>
                                <a onclick="return confirm('Delete product <?=$d->name?>?');"
                                href="<?=App::config('url')?>product/delete/<?=$d->id?>"><i class="bi bi-trash3-fill"></i></a>
                            <?php else: ?>
                                <i title="Can not delete - Product on Cycle" class="bi bi-trash3-fill" style="color: gray"></i>
                            <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
    </div>
<?php else: ?>
    <div class="card">
        <table class="table table-striped">
            <thead>
                <tr class="table-warning">
                    <th scope="col">Name</th>
                    <th scope="col">Color</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($data as $d):?>
                    <tr>
                        <td><?=$d->name?></td>
                        <td><?=$d->color?></td>
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
<br>
<?php include 'pagination.phtml' ?>