<legend>Insert New Product</legend>

<form action="" method="post">
    
    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="name">Product Name*</label>
        <input type="text" name="name" class="form-control"  id="name" value="<?=$e->name?>">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="color">Color</label>
        <input type="text" class="form-control" value="<?=$e->color?>" name="color" id="color">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="price">Price*</label>
        <input type="text" class="form-control" value="<?=$e->price?>" name="price" id="price">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="customer">Customer</label>
        <input type="text" class="form-control" value="<?=$e->customer?>" name="customer" id="customer">
    </div>

    <?=$message?><br>

    <!-- Button trigger modal -->
    <button type="submit" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Add Product
    </button>

    <a href="<?=App::config('url')?>product/index">
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Abort
    </button></a>
    
</form>