<h3 class="display-3">Employees on Shifts</h3>
<a href="<?=App::config('url')?>workershift/new"><button type="button" class="btn btn-outline-primary btn-lg">Add new</button></a>
<br>
***
<div class="card">
    <table class="table table-striped table-responsive">
    <thead>
        <tr class="table-warning">
            <th scope="col">Name</th>
            <th scope="col">Shift</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
        <tbody>
            <?php foreach($data as $d):?>
                <tr>
                    <td><?=$d->name?> <?=$d->surname?></td>
                    <td><?=$d->shift?></td>
                    <td>
                        <a href="<?=App::config('url')?>workershift/update/<?=$d->id?>"><i class="bi bi-pencil-square"></i></a>
                        <?php if($d): ?>

                        <a onclick="return confirm('Delete employee <?=$d->name?> <?=$d->surname?>?');"
                        href="<?=App::config('url')?>workershift/delete/<?=$d->id?>"><i class="bi bi-trash3-fill"></i></a>
                        <?php else: ?>
                            <i title="Can not delete" 
                            class="bi bi-trash3-fill" style="color: gray"></i>
                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>