<?php
//if(!isset($email)) {$email='';}
if(!isset($e->confirmpw)) {$e->confirmpw='';}
?>
<legend>Insert New Operator</legend>

<form action="" method="post">
    
    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="name">Name</label>
        <input type="text" name="name" class="form-control"  id="name" value="<?=$e->name?>">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="surname">Surname</label>
        <input type="text" name="surname" class="form-control"  id="surname" value="<?=$e->surname?>">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="email">Email</label>
        <input type="text" class="form-control" value="<?=$e->email?>" name="email" id="email">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="password">Password</label>
        <input type="password" class="form-control" value="<?=$e->password?>" name="password" id="password">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="confirmpw">Confirm Password</label>
        <input type="password" class="form-control" value="<?=$e->confirmpw?>" name="confirmpw" id="confirmpw">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        
        <input type="radio" class="form-check form-check-inline" name="role" id="admin" value="admin"
        <?php if($e->role) echo 'checked="checked"'; ?>>
        <label for="admin">Administrator</label>
        
        <input type="radio" class="form-check form-check-inline" name="role" id="oper" value="oper"
        <?php if(!$e->role) echo 'checked="checked"'; ?>>
        <label for="oper">Operator</label>
        
    </div>

    <hr>

    <?=$message?><br>

    <!-- Button trigger modal -->
    <button type="submit" class="btn btn-outline-success"  data-bs-target="#staticBackdrop">
    Add Operator
    </button>

    <a href="<?=App::config('url')?>operator/index">
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Abort
    </button></a>
    
</form>