<legend>Insert New Operator</legend>

<form action="" method="post">
    
    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="name">Name</label>
        <input type="text" name="name" class="form-control"  id="name" value="<?=$e->name?>">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="surname">Surname</label>
        <input type="text" name="surname" class="form-control"  id="surname" value="<?=$e->surname?>">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="email">Email</label>
        <input type="text" class="form-control" value="<?=$e->email?>" name="email" id="email">
    </div>
<!--
    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="password">Password</label>
        <input type="text" class="form-control" value="<?=$e->password?>" name="password" id="password">
    </div>

    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="role">Role</label>
        <input type="text" class="form-control" value="<?=$e->role?>" name="role" id="role">
    </div>
-->
    <div class="mb-3 row" style="max-width:400px; margin: auto;">
        <label for="role">Role</label>    
        <select class="form-select form-select-md" aria-label=".form-select-sm example">
            <option selected value="oper" <?php if($e->role) ; ?>>Operator</option>
            <option value="admin">Administrator</option>
        </select>
    </div>

    NOT WORKING JUST YET
    


    <?=$message?><br>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Add Operator
    </button>

    <a href="<?=App::config('url')?>operator/index">
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Abort
    </button></a>

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Add Operator</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Save changes!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>
    
</form>