<h3 class="display-3">Select</h3><br> 
<div class="row">
    <div class="col-sm-6 mb-3 mb-sm-0">
        <div class="card">
        <div class="card-body">
            <h5 class="card-title">Products</h5>
            <p class="card-text">Products overview.</p>
            <img src="<?=App::config('url')?>public/img/produkt.jpeg" class="figure-img img-fluid rounded" alt="..." style="max-height: 400px;">
            <a href="<?=App::config('url');?>product/index"><button type="button" class="btn btn-outline-primary btn-lg">Product</button></a>
        </div>
        </div>
    </div>
    <div class="col-sm-6 mb-3 mb-sm-0">
        <div class="card">
        <div class="card-body">
            <h5 class="card-title">Production cycle</h5>
            <p class="card-text">Production cycle overview.</p>
            <img src="<?=App::config('url')?>public/img/geiss.jpg" class="figure-img img-fluid rounded" alt="..." style="max-height: 400px;">
            <a href="<?=App::config('url');?>cycle/index"><button type="button" class="btn btn-outline-primary btn-lg">Cycle</button></a>
        </div>
        </div>
    </div>
</div>