<h3 class="display-3">About Us</h3><br>
<img src="<?=App::config('url')?>public/img/productplast.jpg" class="img-fluid rounded" alt="...">

<div class="container"><br>
    
    <figcaption class="figure-caption" style="font-size: 25px;">
        <h3>Product plast is one of Scandinavia's leading manufacturers of vacuum formed thermoplastics. We manufacture custom-made specialty products in thermoplastics for industry and other purposes. The export share is substantial and increasing.
        <br>The company was established in 1972 and is privately owned. The location 20 km west of Kristiansand in the south of Norway provides good communication with Scandinavia and the rest of the continent.</h3>
        <hr>
        <h4>is equipped with modern and efficient production equipment and competent employees who can solve most of the challenges the market requires.
        <hr>
        <h4>has an ambitious slogan; ”Correct solution, at the right time, with the correct quality”. 
        <hr>
        <h4>We strive to acheive this through a special commitment to 4 main areas:<br>
        High competance, Flexibility, Security of supply, Surplus / Solidity
    </figcaption>
        
</div>
<hr>
<h5 class="display-5"> Management </h5>
<p class="card-text"><small class="text-muted">***</small></p>
<div class="card-group">
    <div class="card">
        <img src="<?=App::config('url')?>public/img/direktor.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">General director Jon Trondlag</h5>
            <p class="card-text">He deals with management and executive tasks in production and service organizations and companies and is responsible for operations, fulfillment of organizational goals, management of people, organizational processes and finances.</p>
            
        </div>
    </div>
    <div class="card">
        <img src="<?=App::config('url')?>public/img/prodaja.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Sales manager Marko Maric</h5>
            <p class="card-text">The main postulate of sales is - if you want to achieve success in sales, you need to help enough people to get what they want. If you have ever tried to sell something, you probably soon realized that many others are selling the same product.</p>
            
        </div>
    </div>
    <div class="card">
        <img src="<?=App::config('url')?>public/img/smjena1.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Shift manager Narko Nikolicic</h5>
            <p class="card-text">Manages the shift and schedules employees on individual machines with an indication of the best possible productivity. He keeps records of the working hours of the employees in his shift. Prepares and manages production according to the specification and in agreement with the production manager, controls the operation of machines and employees.</p>
            
        </div>
    </div>
</div>