<h3 class="display-3">About APP</h3><br>
<img src="<?=App::config('url')?>public/img/ERplast.jpg" class="img-fluid rounded" alt="...">
<div>
    <br>
    <a href="https://github.com/nduric92/PHPmvc" target="_blank"><button type="button" class="btn btn-danger btn-md">GitHub - Repository</button></a>
</div>


<div class="container"><br>
    
    <figcaption class="figure-caption" style="font-size: 25px;">
        <h3>Plast Product app is desigend to follow employes of the company, products, amount of products produced in production and name of person who made them</h3>
        <hr>
        <h4>After login, products can only be visible to operators without admin role. Administrators can create, update or delete products from the app</h4>
        <hr>
        <h4>Operators can insert new production cycle or change existing. Only administrators can delete production cycle!</h4>
        <hr>
        <h4>Administrators can also create Employees, Shifts and update and delete existing. They create Operators with all data, which they use afterwards to login</h4>        
        <hr>
        <br>
        <h4>How to use:<br></h4>
        <h5>
            <ul class="list-group">
                <li class="list-group-item">Administrator create Shift</li>
                <li class="list-group-item">Administrator create Employee and Operator with all required data</li>
                <li class="list-group-item">Administrator create Product</li>
                <li class="list-group-item">Administrator/Operator create production Cycle</li>
            </ul>
        </h5>
    </figcaption>
        
</div>
<hr>
<h5 class="display-5">Creator</h5>
<p class="card-text"><small class="text-muted">***</small></p>
<div class="row justify-content-md-center">
    <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Nemanja Đurić</h5>
                <p class="card-text">Edunova, PP26 - 2022/2023</p>
                <img src="<?=App::config('url')?>public/img/nem.jpg" class="figure-img img-fluid rounded" alt="..." style="max-height: 400px;">
                <a href="https://github.com/nduric92" target="_blank"><button type="button" class="btn btn-outline-primary btn-lg">GitHub</button></a>
            </div>
        </div>
    </div>
</div>