<h3 class="display-3">Contact Us!</h3><br>

<div class="card">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d8434.75159944721!2d7.7831663!3d58.0946724!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x546df78b0cbb5c2c!2sGyli%20Plast%20AS!5e0!3m2!1shr!2shr!4v1677494054978!5m2!1shr!2shr"
        width="100%" height="450" style="border:0;" 
        allowfullscreen="" loading="lazy" 
        referrerpolicy="no-referrer-when-downgrade">
    </iframe>
</div>

<br>

<div class="card">
  <div class="card-header">
    <h3>Contact</h3>
  </div>
  <div class="card-body">
    <h5 class="card-title">Plast Product</h5>
    <p class="card-text">Phone: +47 38 05 44 44</p>
    <p class="card-text">Mailing Address: Boks 964, 4682 Søgne</p>
    <h5 class="card-title">Location</h5>
    <p class="card-text">In the south end of Norway, about 20km west of Kristiansand. The location is in close proximity to ferry routes, 
        airports and European roads, ensuring good communication to
        Scandinavia and the rest of the continent.</p>
  </div>
</div>