
    <h3 class="display-3">Welcome to Plast Product</h3><br>


<div id="carouselExampleIndicators" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="d-flex justify-content-center">
                <img src="<?=App::config('url')?>public/img/volvoplastic.jpg" class="d-block w-100 rounded" alt="...">
            </div>
        </div>
        <div class="carousel-item">
            <div class="d-flex justify-content-center">
                <img src="<?=App::config('url')?>public/img/people.jpg" class="d-block w-100 rounded" alt="...">
            </div>
        </div>
        <div class="carousel-item">
            <div class="d-flex justify-content-center">
                <img src="<?=App::config('url')?>public/img/volvoradnik.jpg" class="d-block w-100 rounded" alt="...">
            </div>
        </div>
        <div class="carousel-item">
            <div class="d-flex justify-content-center">
                <img src="<?=App::config('url')?>public/img/volvo1.jpg" class="d-block w-100 rounded" alt="...">
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<figcaption class="figure-caption" style="font-size: 25px;">
    Among our typical products we can mention panels for cars: buses, trucks, construction machines and car conversion. Refrigerant industry: Refrigeration equipment for commercial kitchens, refrigeration units and other related industries.<br>
    <hr>Auxiliary products: Various aids for people with disabilities, such as wheelchairs, scooters, elevators. Display: Various fronts / panels for machines and machines inside the retail store.
</figcaption>



